import Foundation
import MdxKit

/// Fixture-based tests for the MDX/MDD parser. Fixtures are generated by
/// tools/make_fixtures.py using the reference writemdict library.
func runParserTests(_ t: TestHarness) {
    func fixture(_ name: String) -> URL {
        fixturesURL.appendingPathComponent(name)
    }

    /// The lookups every MDX fixture variant must satisfy.
    func checkStandardEntries(_ dict: MdictFile, label: String) throws {
        t.expectEqual(dict.info.entryCount, 56, "\(label): entry count")

        let apple = try dict.lookup("apple")
        t.expect(apple?.contains("a round fruit with firm flesh") == true, "\(label): apple content")
        t.expect(apple?.contains("sound://pron/apple.wav") == true, "\(label): apple audio link")

        let colour = try dict.lookup("colour")
        t.expect(colour?.hasPrefix("@@@LINK=color") == true, "\(label): colour redirect, got \(colour ?? "nil")")

        let naive = try dict.lookup("naïve")
        t.expect(naive?.contains("unicode key test") == true, "\(label): unicode key")

        let filler = try dict.lookup("w037")
        t.expect(filler?.contains("filler entry number 37") == true, "\(label): filler entry")

        t.expectEqual(try dict.lookup("missing-word"), nil, "\(label): absent key")
    }

    t.run("basic.mdx metadata") {
        let dict = try MdictFile(url: fixture("basic.mdx"))
        t.expectEqual(dict.info.title, "Basic Test Dictionary")
        t.expectEqual(dict.info.encoding, .utf8)
        t.expect(dict.info.engineVersion >= 2.0, "engine version")
        t.expect(!dict.info.isMDD, "not MDD")
    }

    t.run("basic.mdx lookups") {
        let dict = try MdictFile(url: fixture("basic.mdx"))
        try checkStandardEntries(dict, label: "basic")
    }

    t.run("basic.mdx indexed entries have sane lengths") {
        let dict = try MdictFile(url: fixture("basic.mdx"))
        let entries = try dict.indexedEntries()
        t.expectEqual(entries.count, 56, "indexed entry count")
        for entry in entries {
            t.expect(entry.recordLength > 0, "zero-length record for \(entry.key)")
        }
        // Reading through the stored (offset, length) must match lookup().
        guard let apple = entries.first(where: { $0.key == "apple" }) else {
            t.expect(false, "apple not in index")
            return
        }
        let direct = try dict.entryText(at: apple.recordOffset, length: Int(apple.recordLength))
        let scanned = try dict.lookup("apple")
        t.expectEqual(direct, scanned ?? "", "offset+length read equals scan read")
    }

    t.run("record data reads across compressed block boundaries") {
        let dict = try MdictFile(url: fixture("basic.mdx"))
        // basic.mdx uses 256-byte record blocks and contains well over 700
        // bytes. This read therefore exercises concatenation of several
        // independently compressed blocks.
        let data = try dict.recordData(at: 0, length: 700)
        t.expectEqual(data.count, 700, "length-bounded multi-block read")
        let text = String(decoding: data, as: UTF8.self)
        t.expect(text.contains("apple"), "starts in the first record block")
        t.expect(text.contains("filler entry"), "continues into later record blocks")
    }

    t.run("encrypted.mdx (Encrypted=2 keyword index)") {
        let dict = try MdictFile(url: fixture("encrypted.mdx"))
        t.expectEqual(dict.info.title, "Encrypted Index Dictionary")
        try checkStandardEntries(dict, label: "encrypted")
    }

    t.run("utf16.mdx") {
        let dict = try MdictFile(url: fixture("utf16.mdx"))
        t.expectEqual(dict.info.encoding, .utf16le)
        try checkStandardEntries(dict, label: "utf16")
    }

    t.run("v1.mdx (format 1.2)") {
        let dict = try MdictFile(url: fixture("v1.mdx"))
        t.expect(dict.info.engineVersion < 2.0, "v1 engine version")
        try checkStandardEntries(dict, label: "v1")
    }

    t.run("nocomp.mdx (compression type 0)") {
        let dict = try MdictFile(url: fixture("nocomp.mdx"))
        try checkStandardEntries(dict, label: "nocomp")
    }

    t.run("basic.mdd resources") {
        let mdd = try MdictFile(url: fixture("basic.mdd"))
        t.expect(mdd.info.isMDD, "is MDD")
        t.expectEqual(mdd.info.encoding, .utf16le, "MDD keys are UTF-16")

        let keys = try mdd.allKeys().map(\.key).sorted()
        t.expectEqual(keys, ["\\apple.png", "\\pron\\apple.wav", "\\style.css"], "MDD keys")

        let png = try mdd.resourceData(path: "\\apple.png")
        t.expect(png?.prefix(8) == Data([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]), "PNG magic")

        // Case-insensitive, slash-agnostic lookup.
        let wav = try mdd.resourceData(path: "/PRON/Apple.WAV")
        t.expect(wav?.prefix(4) == Data("RIFF".utf8), "WAV via normalized path")

        let css = try mdd.resourceData(path: "style.css")
        t.expect(css.map { String(decoding: $0, as: UTF8.self) }?.contains("Georgia") == true, "CSS content")

        t.expectEqual(try mdd.resourceData(path: "missing.bin"), nil, "absent resource")
    }

    t.run("stylesheet substitution") {
        let sheet = ["1": ("<b>", "</b>"), "2": ("<i>", "</i>")]
        let out = MdictFile.applyStylesheet("`1`bold`2`italic", stylesheet: sheet)
        t.expectEqual(out, "<b>bold</b><i>italic</i>")
        t.expectEqual(MdictFile.applyStylesheet("plain text", stylesheet: sheet), "plain text")
    }
}
