import Foundation
import MdxKit
import WebKit

/// Serves dict:// URLs from the dictionary library.
///
/// URL layout (host is always "d" so that the outer page and all entry
/// iframes share one origin, letting the outer page measure iframe heights):
///   dict://d/<dictUUID>/entry?word=<normalized key>   entry HTML for one dictionary
///   dict://d/<dictUUID>/<resource path>               image/CSS/audio/… from the MDD
final class DictSchemeHandler: NSObject, WKURLSchemeHandler {
    static let scheme = "dict"

    private weak var appState: AppState?

    init(appState: AppState) {
        self.appState = appState
    }

    func webView(_ webView: WKWebView, start urlSchemeTask: WKURLSchemeTask) {
        guard let url = urlSchemeTask.request.url else {
            urlSchemeTask.didFailWithError(URLError(.badURL))
            return
        }
        let (data, mimeType) = respond(to: url)
        guard let data else {
            urlSchemeTask.didFailWithError(URLError(.fileDoesNotExist))
            return
        }
        let response = URLResponse(
            url: url, mimeType: mimeType, expectedContentLength: data.count,
            textEncodingName: mimeType.hasPrefix("text/") ? "utf-8" : nil
        )
        urlSchemeTask.didReceive(response)
        urlSchemeTask.didReceive(data)
        urlSchemeTask.didFinish()
    }

    func webView(_ webView: WKWebView, stop urlSchemeTask: WKURLSchemeTask) {
        // Responses are produced synchronously in start; nothing to cancel.
    }

    private func respond(to url: URL) -> (Data?, String) {
        guard let library = appState?.library else { return (nil, "text/plain") }

        var components = url.path.split(separator: "/").map(String.init)
        guard !components.isEmpty else { return (nil, "text/plain") }
        let uuid = components.removeFirst()

        if components == ["entry"] {
            let query = URLComponents(url: url, resolvingAgainstBaseURL: false)
            let word = query?.queryItems?.first(where: { $0.name == "word" })?.value ?? ""
            let html = EntryPageBuilder.entryDocument(
                for: word, dictionaryUUID: uuid, library: library
            )
            return (Data(html.utf8), "text/html")
        }

        // Everything else is a resource path inside this dictionary.
        let resourcePath = components.joined(separator: "/")
        if !resourcePath.isEmpty,
           let data = try? library.resource(path: resourcePath, dictionaryUUID: uuid) {
            return (data, Self.mimeType(forPath: resourcePath))
        }

        // Root-relative requests generated by dictionary JS resolve to
        // dict://d/<path> and lose the UUID; the first component is then not
        // a dictionary. Search all enabled dictionaries for the full path.
        if !library.isKnownDictionaryUUID(uuid) {
            let fullPath = ([uuid] + components).joined(separator: "/")
            if let data = try? library.resourceSearchingAllDictionaries(path: fullPath) {
                return (data, Self.mimeType(forPath: fullPath))
            }
        }
        return (nil, "text/plain")
    }

    static func mimeType(forPath path: String) -> String {
        switch (path as NSString).pathExtension.lowercased() {
        case "html", "htm": return "text/html"
        case "css": return "text/css"
        case "js": return "text/javascript"
        case "png": return "image/png"
        case "jpg", "jpeg": return "image/jpeg"
        case "gif": return "image/gif"
        case "svg": return "image/svg+xml"
        case "webp": return "image/webp"
        case "bmp": return "image/bmp"
        case "ico": return "image/x-icon"
        case "woff": return "font/woff"
        case "woff2": return "font/woff2"
        case "ttf": return "font/ttf"
        case "otf": return "font/otf"
        case "mp3": return "audio/mpeg"
        case "wav": return "audio/wav"
        case "ogg", "oga": return "audio/ogg"
        case "mp4": return "video/mp4"
        case "json": return "application/json"
        default: return "application/octet-stream"
        }
    }
}
